import { useEffect, useRef, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { 
  initFacebookPixelWithLogging, 
  trackPageViewEvent, 
  trackViewContentEvent, 
  AdvancedMatchingData,
  getFbcFbpCookies,
  waitForFbp
} from '@/utils/fbpixel';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { useToast } from '@/hooks/use-toast';
import { Toaster } from '@/components/ui/toaster';
import { Card, CardContent } from '@/components/ui/card';
import { ArrowLeft, Copy, CreditCard, User, CheckCircle, ShieldCheck, Loader2, Flame } from 'lucide-react';

const WebinarPriaSusis = () => {
    const { toast } = useToast();
    const hasFiredPixelsRef = useRef(false);
    const sentEventIdsRef = useRef(new Set<string>());
    const addPaymentInfoFiredRef = useRef(false);
    const purchaseFiredRef = useRef(false);
    const isProcessingRef = useRef(false);

    // Form State
    const [userName, setUserName] = useState('');
    const [userEmail, setUserEmail] = useState('');
    const [phoneNumber, setPhoneNumber] = useState('');
    const [selectedPaymentMethod, setSelectedPaymentMethod] = useState('QRIS');
    const [loading, setLoading] = useState(false);
    const [paymentData, setPaymentData] = useState<any>(null);
    const [showPaymentInstructions, setShowPaymentInstructions] = useState(false);
    
    // Hardcoded for this specific webinar
    const productNameBackend = 'webinar_el'; 
    const displayProductName = 'Webinar The Kings Return';
    const productPrice = 200000;
    const pixelId = '3319324491540889'; 

    const paymentMethods = [
        { code: 'QRIS', name: 'QRIS', description: 'Scan pakai GoPay, OVO, Dana, ShopeePay, BCA Mobile, dll' },
        { code: 'BCAVA', name: 'BCA Virtual Account', description: 'Transfer otomatis via BCA' },
        { code: 'BNIVA', name: 'BNI Virtual Account', description: 'Transfer otomatis via BNI' },
        { code: 'BRIVA', name: 'BRI Virtual Account', description: 'Transfer otomatis via BRI' },
        { code: 'MANDIRIVA', name: 'Mandiri Virtual Account', description: 'Transfer otomatis via Mandiri' },
        { code: 'PERMATAVA', name: 'Permata Virtual Account', description: 'Transfer otomatis via Permata' },
    ];

    const formatCurrency = (amount: number) => {
        return new Intl.NumberFormat('id-ID', {
            style: 'currency',
            currency: 'IDR',
            minimumFractionDigits: 0,
            maximumFractionDigits: 0,
        }).format(amount);
    };

    const copyToClipboard = (text: string) => {
        navigator.clipboard.writeText(text);
        toast({
            title: "Berhasil Disalin",
            description: "Teks telah disalin ke clipboard",
        });
    };

    // Helper to send CAPI events - STRICTLY FOR ADDPAYMENTINFO ONLY
    const sendCapiEvent = async (eventName: string, eventData: any, eventId?: string) => {    
      try {
        // 🛡️ DEDUPLICATION CHECK
        if (eventId && sentEventIdsRef.current.has(eventId)) {
          return;
        }
        if (eventId) {
          sentEventIdsRef.current.add(eventId);
        }

        // ⏳ Wait for FBP to be generated by the browser pixel before sending CAPI
        await waitForFbp();

        const { data: { session } } = await supabase.auth.getSession();
        
        // IDENTIC URL AS REQUESTED
        const body: any = {
          pixelId,
          eventName,
          customData: eventData,
          eventId: eventId,
          eventSourceUrl: window.location.href,
          testCode: 'TEST33364'
        };

        // Get FBC and FBP from cookies using the utility function
        const { fbc, fbp } = getFbcFbpCookies();

        const userData: any = {
          client_user_agent: navigator.userAgent,
        };

        // Prioritize form input email/phone/name, then authenticated user email/phone/name
        let rawName = userName;
        if (userEmail) {
            userData.email = userEmail;
        } else if (session?.user?.email) {
            userData.email = session.user.email;
        }
        
        if (phoneNumber) {
            userData.phone = phoneNumber;
        } else if (session?.user?.user_metadata?.phone) {
            userData.phone = session.user.user_metadata.phone;
        }
        
        if (!rawName && session?.user?.user_metadata?.full_name) {
            rawName = session.user.user_metadata.full_name;
        }

        if (rawName) {
            const nameParts = rawName.trim().split(/\s+/);
            userData.fn = nameParts[0];
            if (nameParts.length > 1) {
                userData.ln = nameParts.slice(1).join(' ');
            }
        }

        if (session?.user?.id) {
          userData.external_id = session.user.id;
        }

        const fbIdentity = session?.user?.identities?.find(id => id.provider === 'facebook');
        if (fbIdentity) {
          userData.db_id = fbIdentity.id;
        }

        if (fbc) userData.fbc = fbc;
        if (fbp) userData.fbp = fbp;
        
        body.userData = userData;

        // IDENTIC URL AS REQUESTED
        const { error } = await supabase.functions.invoke('capi-universal', { body });
        
        if (error) {
            console.error(`❌ CAPI Error for ${eventName}:`, error);
        }
      } catch (err) {
        console.error('Failed to send CAPI event (Critical):', err);
      }
    };

    // Pixel Tracking - PIXEL ONLY FOR VIEWCONTENT & PAGEVIEW
    useEffect(() => {
      const initPixel = async () => {
        if (typeof window !== 'undefined' && !hasFiredPixelsRef.current) {
          hasFiredPixelsRef.current = true;
          
          const { data: { session } } = await supabase.auth.getSession();
          const { fbc, fbp } = getFbcFbpCookies();
          
          const userData: AdvancedMatchingData = {};
          
          if (session?.user?.id) {
            userData.external_id = session.user.id;
          }
          
          const fbIdentity = session?.user?.identities?.find(id => id.provider === 'facebook');
          if (fbIdentity) {
            userData.db_id = fbIdentity.id;
          }
          
          if (fbc) userData.fbc = fbc;
          if (fbp) userData.fbp = fbp;

          initFacebookPixelWithLogging(pixelId, userData);

          // 1. PageView (PIXEL ONLY)
          const pageEventId = `pageview-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
          trackPageViewEvent({}, pageEventId, pixelId, userData, 'TEST33364');

          // 2. ViewContent (PIXEL ONLY)
          const viewContentEventId = `viewcontent-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
          trackViewContentEvent({
            content_name: displayProductName,
            content_ids: [productNameBackend],
            content_type: 'product',
            value: productPrice,
            currency: 'IDR'
          }, viewContentEventId, pixelId, userData, 'TEST33364');
          
          // NO CAPI CALLS HERE
        }
      };

      initPixel();
    }, []);

    const handleCreatePayment = async () => {
        if (isProcessingRef.current) return;

        if (!userName || !userEmail || !phoneNumber || !selectedPaymentMethod) {
            toast({
                title: "Data Tidak Lengkap",
                description: "Mohon lengkapi nama, email, no. whatsapp, dan metode pembayaran.",
                variant: "destructive",
            });
            return;
        }

        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(userEmail)) {
            toast({
                title: "Email Tidak Valid",
                description: "Mohon masukkan alamat email yang benar.",
                variant: "destructive",
            });
            return;
        }

        isProcessingRef.current = true;
        setLoading(true);

        try {
             // Track AddPaymentInfo (CAPI ONLY - NO PIXEL)
             if (!addPaymentInfoFiredRef.current) {
                addPaymentInfoFiredRef.current = true;
                const addPaymentInfoEventId = `addpaymentinfo-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
                
                await sendCapiEvent('AddPaymentInfo', {
                  content_ids: [productNameBackend],
                  content_type: 'product',
                  value: productPrice,
                  currency: 'IDR'
                }, addPaymentInfoEventId);
            }

            const { fbc, fbp } = getFbcFbpCookies();

            // IDENTIC URL AS REQUESTED
            const { data, error } = await supabase.functions.invoke('tripay-create-payment', {
                body: {
                  subscriptionType: productNameBackend,
                  paymentMethod: selectedPaymentMethod,
                  userName: userName,
                  userEmail: userEmail,
                  phoneNumber: phoneNumber,
                  amount: productPrice,
                  quantity: 1,
                  productName: displayProductName,
                  userId: null,
                  fbc,
                  fbp
                }
            });

            if (error || !data?.success) {
                let errorMessage = data?.error || error?.message || "Terjadi kesalahan sistem.";
                toast({
                  title: "Gagal Memproses",
                  description: errorMessage,
                  variant: "destructive",
                });
                return;
            }

            if (data?.success) {
                setPaymentData(data);
                setShowPaymentInstructions(true);
                toast({
                  title: "Slot Diamankan!",
                  description: "Silakan selesaikan pembayaran Anda.",
                });
                window.scrollTo({ top: 0, behavior: 'smooth' });
            }

        } catch (error: any) {
            toast({
              title: "Error",
              description: "Gagal menghubungi server pembayaran.",
              variant: "destructive",
            });
        } finally {
            setLoading(false);
            isProcessingRef.current = false;
        }
    };

    // Realtime Payment Listener
    useEffect(() => {
        if (!showPaymentInstructions || !paymentData?.tripay_reference) return;
        
        const channel = supabase
          .channel(`payment-${paymentData.tripay_reference}`)
          .on('postgres_changes', { 
            event: 'UPDATE', 
            schema: 'public', 
            table: 'global_product', 
            filter: `tripay_reference=eq.${paymentData.tripay_reference}`
          }, (payload) => {
            if (payload.new?.status === 'PAID') {
              if (purchaseFiredRef.current) return;
              purchaseFiredRef.current = true;
    
              toast({
                  title: "LUNAS! Tahta Kembali.",
                  description: "Pembayaran berhasil. Cek email untuk akses Webinar.",
                  duration: 5000, 
                  variant: "default"
              });
              // NO PIXEL OR CAPI FOR PURCHASE AS REQUESTED
            }
          }).subscribe();
    
        return () => { supabase.removeChannel(channel); };
    }, [showPaymentInstructions, paymentData]);

    // ==========================================
    // 📝 STRATEGI COPYWRITING: PRIA/SUAMI SUSIS (POLARISM SOPAN)
    // ==========================================
    const content = {
        // 1. TARGET BADGE
        targetBadge: "KHUSUS SUAMI YANG INGIN DIHARGAI KEMBALI",
        
        // 2. HERO SECTION
        headline: "Sudah Nafkahi Lahir Batin, Tapi Masih Dianggap 'Patung' di Rumah Sendiri?",
        subheadline: "Ketika diam dianggap lemah, dan bicara dianggap mengajak ribut. Kembalikan wibawa Anda sebelum rumah tangga terasa seperti neraka dingin.",

        // 3. PAIN SECTION
        painTitle: "Apakah Kebisuan Ini Yang Anda Rasakan, Pak?",
        painPoints: [
            { icon: "🔇", text: <span><strong>"Suara Tidak Didengar."</strong> Pendapat Anda selalu dipatahkan, seolah Anda anak kecil yang tidak tahu apa-apa soal rumah tangga.</span> },
            { icon: "📉", text: <span><strong>"Wibawa Tergerus."</strong> Istri lebih dominan mengatur segalanya. Anda merasa seperti 'tamu' atau 'supir' di rumah yang Anda bayar cicilannya.</span> },
            { icon: "❄️", text: <span><strong>"Intimasi Membeku."</strong> Sentuhan fisik menjadi barang langka. Anda harus 'mengemis' kasih sayang pada pasangan sendiri.</span> }
        ],

        // 4. LOGIC TRAP
        logicTitle: "Jebakan: 'Happy Wife, Happy Life'",
        logicDescription: "Banyak suami terjebak doktrin: <em>'Asal istri senang, saya ngalah saja.'</em><br/><br/><strong>ITU KELIRU BESAR.</strong><br/>Wanita tidak menghormati pria yang selalu mengalah karena takut. Wanita mendambakan <strong>Pemimpin</strong>, bukan Pengikut. Semakin Anda lembek, semakin dia kehilangan rasa hormat.",

        // 5. AGITATION
        agitationTitle: "THE ROOMMATE SYNDROME: Sindrom Teman Kos",
        agitationText: [
            "Maaf saya harus keras di sini, Pak. Jika ini dibiarkan, Anda tidak lagi dianggap Suami.",
            "Anda akan berubah status menjadi <strong>'Teman Kos'</strong> atau <strong>'Partner Bisnis'</strong> yang tugasnya hanya membayar tagihan.",
            "Tanpa polaritas energi maskulin yang kuat, rasa cinta akan berubah menjadi rasa kasihan. Dan tidak ada wanita yang bergairah pada pria yang ia kasihani."
        ],
        agitationBullets: [
            { trigger: "Anda Terus Mengalah?", result: "Istri Makin Dominan." },
            { trigger: "Anda Takut Konflik?", result: "Respek Hilang Total." },
            { trigger: "Skip Webinar Ini?", result: "Persiapkan Diri Digantikan." }
        ],
        agitationClosing: "Masih mau bertahan dalam diam yang menyakitkan?",

        // 6. THE SHIFT (SOLUTION)
        shiftTitle: "The King's Return: Kembalinya Sang Raja",
        shiftDescription: "Kita tidak akan belajar menjadi suami galak atau kasar. Itu kuno. Kita akan mengaktifkan <strong>'Silent Authority'</strong>. Aura wibawa yang membuat istri segan dan lembut secara otomatis tanpa Anda perlu membentak.",
        shiftResults: [
            "🔥 Mengembalikan 'Spark' & Gairah istri yang sudah lama mati.",
            "🛡️ Menjadi Pemimpin yang didengar kata-katanya tanpa perlu emosi.",
            "👑 Merasakan kembali nikmatnya menjadi KEPALA keluarga yang sesungguhnya."
        ],

        // 7. WEBINAR DETAILS
        webinarTitle: 'WEBINAR: "THE KING\'S RETURN - 22 FEB 2026"',
        eventDate: "Minggu, 22 Februari 2026 | 17:00 WIB",
        curriculum: [
            { title: 'The Masculine Core', desc: 'Cara mengisi ulang tangki "Kewibawaan" yang bocor akibat terlalu sering mengalah.' },
            { title: 'Polarity Switch', desc: 'Teknik psikologi membalikkan dominasi istri menjadi kelembutan (Feminine Surrender) dalam 3 detik.' },
            { title: 'Authority Language', desc: 'Seni komunikasi bawah sadar agar setiap ucapan Anda memiliki bobot perintah yang dipatuhi dengan sukarela.' }
        ],

        // 8. PRICING & CTA
        priceAnchor: "Rp 5.000.000,-",
        priceReal: "Rp 200.000,-",
        ctaButton: "👉 SAYA AMBIL KEMBALI TAHTA SAYA",

        // 9. STEPS
        steps: [
            { title: "Langkah 1: Komitmen", desc: "Klik tombol di bawah. Ini bukan soal uang 200rb, ini soal harga diri Anda yang tak ternilai." },
            { title: "Langkah 2: Masuk Circle", desc: "Anda akan bergabung dengan para pria yang juga sedang berjuang mengembalikan marwahnya." },
            { title: "Langkah 3: Transformasi", desc: "Hadir Live 22 Februari jam 17:00 WIB. Jangan terlambat. Raja tidak pernah terlambat." }
        ],

        // 10. FAQ
        faq: [
            { q: "Apakah ini mengajarkan saya jadi suami otoriter?", a: "Sama sekali tidak. Otoriter adalah tanda kelemahan. Kami mengajarkan Wibawa Sejati (Authentic Authority) yang menenangkan, bukan menakutkan." },
            { q: "Istri saya sudah sangat keras, apa masih bisa?", a: "Kerasnya istri adalah respons alamiah dari kurangnya sisi maskulin suami. Saat Anda berubah, dia TERPAKSA berubah secara biologis. Ini hukum alam." },
            { q: "Apa webinar ini rahasia?", a: "Tentu. Privasi Anda prioritas kami. Di grup nanti Anda boleh menggunakan nama samaran jika itu membuat Anda nyaman." },
            { q: "Bagaimana kalau saya tidak punya waktu?", a: "Pria yang tidak punya waktu untuk memimpin keluarganya, akan punya banyak waktu untuk menyesali perceraiannya. Luangkan waktu 2 jam ini." }
        ]
    };

    const founderImages = [
        "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/siapael/siapael1.jpeg",
        "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/siapael/siapael2.jpeg"
    ];

    // IDENTIC AMOUNT OF TESTIMONIALS
    const videoTestimonials = [
        { name: "Agus Mulyadi, SH., MH.", title: "Kepala Intelijen Pangandaran", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/AGUS_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/agus.jpg", thumbnail: "🎖️" },
        { name: "Dr. Gumilar", title: "Hipnoterapist & Pemimpin Yayasan", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/DRVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/dr.jpg", thumbnail: "⚕️" },
        { name: "Habib Umar", title: "Pemimpin Pondok Pesantren Atsaqofah", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/HABIBVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/habib.jpg", thumbnail: "🕌" },
        { name: "Bambang S.", title: "Suami (Reclaim His Authority)", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/UMIVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/umi.jpg", thumbnail: "👑" },
        { name: "Hendra Wijaya", title: "Wiraswasta & Pemimpin Keluarga", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/FELVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/felicia.jpg", thumbnail: "🛡️" },
        { name: "Andrianto", title: "Professional (Silent Authority)", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/LENA_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/lena.jpg", thumbnail: "⚡" },
        { name: "Rizky", title: "Ayah & Pemimpin Rumah Tangga", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/VIOVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/vio2.jpg", thumbnail: "✨" },
        { name: "Arif", title: "Klien eL Vision", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/arif_inte.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/arif_inte.jpg", thumbnail: "👨‍💻" }
    ];

    const testimonials = [
        { name: "Bambang S.", title: "Karyawan Swasta, 12 Tahun Menikah", image: "👨‍💼", rating: 5, text: "Dulu saya merasa seperti ATM berjalan dan supir pribadi di rumah sendiri. Setelah ikut program eL, wibawa saya kembali tanpa perlu membentak. Istri jadi jauh lebih lembut." },
        { name: "Hendra Wijaya", title: "Wiraswasta", image: "🏗️", rating: 5, text: "Hampir cerai karena istri terlalu dominan dan meremehkan saya. Ternyata kuncinya ada di 'Silent Authority'. Sekarang rumah tangga kami jauh lebih harmonis dan penuh respek." },
        { name: "Andrianto", title: "Manager di Perusahaan Multinasional", verified: true, image: "🎯", rating: 5, text: "Wibawa saya di kantor tinggi, tapi di rumah nol. eL Vision bantu saya kalibrasi ulang energi maskulin. Sekarang kata-kata saya didengar tanpa perlu emosi." },
        { name: "Rizky", title: "Professional & Ayah 2 Anak", verified: true, image: "🏠", rating: 5, text: "Anak-anak dulu lebih dengerin istri daripada saya. Saya merasa kehilangan peran. Webinar ini mengembalikan jati diri saya sebagai pemimpin keluarga yang sesungguhnya." },
        { name: "Donny Kurniawan", title: "Pengusaha Muda", image: "💼", rating: 5, text: "Pernah merasa 'kecil' karena penghasilan istri lebih besar. Sekarang saya paham wibawa bukan soal uang, tapi soal 'Polarity'. Kami jauh lebih bahagia sekarang." },
        { name: "Eko Prasetyo", title: "Karyawan Senior", verified: true, image: "🛡️", rating: 5, text: "Selama ini saya terjebak doktrin 'ngalah demi damai'. Ternyata itu yang bikin respek hilang. Setelah belajar dari eL, saya tahu cara memimpin dengan benar." },
        { name: "Yusuf", title: "Arsitek", verified: true, image: "📐", rating: 5, text: "Metode eL Vision selama 6 minggu sepenuhnya mengubah perspektif saya dan melihat bahwa metode modern ini memberikan hasil yang cepat." },
        { name: "Fajar Ramadan", title: "Klien eL Vision", verified: true, image: "👑", rating: 5, text: "Komunikasi yang tadinya penuh tuntutan dan bentakan, berubah menjadi rasa hormat yang tulus. Saya merasa kembali menjadi 'Raja' di istana saya sendiri." }
    ];

    if (showPaymentInstructions && paymentData) {
        return (
          <div className="min-h-screen bg-slate-900 pb-20 font-sans text-slate-100">
            <div className="max-w-md mx-auto bg-slate-800 min-h-screen shadow-2xl border-x border-slate-700">
              <div className="p-4 bg-amber-700 text-white flex items-center gap-2 sticky top-0 z-10 shadow-lg">
                <Button variant="ghost" size="icon" onClick={() => setShowPaymentInstructions(false)} className="text-white hover:bg-amber-800">
                  <ArrowLeft className="w-6 h-6" />
                </Button>
                <h1 className="font-bold text-lg">Selesaikan Pembayaran</h1>
              </div>
    
              <div className="p-6 space-y-6">
                <div className="text-center">
                    <p className="text-slate-400">Total Tagihan</p>
                    <p className="text-3xl font-bold text-amber-500">{formatCurrency(paymentData.amount)}</p>
                    <div className="mt-2 inline-block px-3 py-1 bg-amber-900/30 text-amber-400 rounded-full text-sm font-medium border border-amber-800/50">
                        Menunggu Pembayaran
                    </div>
                </div>
    
                <Card className="border border-slate-700 bg-slate-900 text-slate-100">
                  <CardContent className="pt-6 space-y-4">
                    <div className="space-y-2 border-b border-slate-800 pb-4 mb-4">
                        <Label className="text-slate-400">Nomor Referensi</Label>
                        <div className="flex items-center justify-between bg-slate-800 p-2 rounded border border-slate-700">
                            <span className="font-mono text-sm text-amber-500">{paymentData.tripay_reference}</span>
                            <Button size="sm" variant="ghost" onClick={() => copyToClipboard(paymentData.tripay_reference)} className="h-8 w-8 p-0 text-slate-400 hover:text-amber-500">
                                <Copy className="w-3 h-3" />
                            </Button>
                        </div>
                    </div>

                    {paymentData.qrUrl && (
                        <div className="flex flex-col items-center">
                            <img src={paymentData.qrUrl} alt="QRIS" className="w-64 h-64 object-contain border border-slate-700 rounded-lg bg-white" />
                            <p className="text-sm text-slate-500 mt-2 text-center">Scan QR di atas menggunakan aplikasi e-wallet atau mobile banking Anda.</p>
                        </div>
                    )}
                    
                    {paymentData.payCode && (
                        <div className="space-y-2">
                            <Label className="text-slate-400">Kode Bayar / Virtual Account</Label>
                            <div className="flex items-center justify-between bg-slate-800 p-3 rounded-lg border border-slate-700">
                                <span className="font-mono text-xl font-bold tracking-wider text-amber-500">{paymentData.payCode}</span>
                                <Button size="sm" variant="ghost" onClick={() => copyToClipboard(paymentData.payCode)} className="text-slate-400 hover:text-amber-500">
                                    <Copy className="w-4 h-4" />
                                </Button>
                            </div>
                        </div>
                    )}
    
                    <div className="bg-amber-950/40 p-3 rounded text-sm text-amber-300 border border-amber-900/50">
                        <p><strong>PENTING:</strong> Lakukan pembayaran sebelum waktu habis. Sistem akan otomatis memverifikasi dan mengirim akses ke Email Anda.</p>
                    </div>
                  </CardContent>
                </Card>
                
                <div className="text-center">
                   <Button variant="outline" className="w-full gap-2 border-slate-700 text-slate-400 hover:bg-slate-800 hover:text-white" onClick={() => window.open(`https://wa.me/62895325633487?text=Halo admin, saya sudah bayar untuk order Webinar Rezeki ${paymentData.tripay_reference} tapi belum aktif.`, '_blank')}>
                       Bantuan Admin
                   </Button>
                </div>
              </div>
            </div>
          </div>
        );
      }

    return (
        <div style={{
            fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif",
            background: "linear-gradient(135deg, #020617 0%, #0f172a 50%, #1e293b 100%)", // DARK THEME
            color: "#f1f5f9", // Light text
            lineHeight: 1.6,
            minHeight: "100vh"
        }}>
            <Toaster />
            <div style={{ maxWidth: "680px", margin: "0 auto", padding: "20px" }}>
                
                {/* 1. HEADER LOGO */}
                <div style={{ textAlign: "center", padding: "20px 0", marginBottom: "20px" }}>
                    <div style={{ fontSize: "24px", fontWeight: 800, color: "#f59e0b", letterSpacing: "3px", textShadow: "0 0 10px rgba(245, 158, 11, 0.5)" }}>eL VISION</div>
                    <div style={{ fontSize: "12px", color: "#94a3b8", textTransform: "uppercase", letterSpacing: "2px" }}>The King's Series</div>
                </div>

                <div style={{ textAlign: "center", padding: "40px 20px", background: "rgba(15, 23, 42, 0.8)", borderRadius: "25px", marginBottom: "30px", boxShadow: "0 20px 50px rgba(0,0,0,0.5)", border: "1px solid rgba(245, 158, 11, 0.2)", backdropFilter: "blur(10px)" }}>
                    <span style={{ background: "linear-gradient(90deg, #78350f, #92400e)", color: "#fbbf24", padding: "10px 25px", borderRadius: "50px", fontSize: "14px", fontWeight: "900", marginBottom: "25px", display: "inline-block", letterSpacing: "1px", border: "1px solid #b45309", boxShadow: "0 4px 15px rgba(245, 158, 11, 0.2)" }}>
                        {content.targetBadge}
                    </span>
                    <h1 style={{ fontSize: "28px", fontWeight: 800, color: "#ffffff", marginBottom: "15px", lineHeight: 1.3, textShadow: "0 2px 10px rgba(0,0,0,0.5)" }}>{content.headline}</h1>
                    <p style={{ fontSize: "16px", color: "#cbd5e1", marginBottom: "0px", lineHeight: 1.6 }}>{content.subheadline}</p>
                    <div style={{ marginTop: "25px", background: "rgba(255,255,255,0.05)", display: "inline-block", padding: "10px 20px", borderRadius: "10px", border: "1px solid rgba(255,255,255,0.1)", color: "#fbbf24" }}>
                        🗓️ Event: <strong>{content.eventDate}</strong>
                    </div>
                </div>

                {/* 3. PAIN SECTION */}
                <div style={{ background: "#1e293b", padding: "30px 25px", borderRadius: "25px", marginBottom: "30px", borderLeft: "5px solid #b91c1c", boxShadow: "0 10px 30px rgba(0,0,0,0.3)" }}>
                    <h2 style={{ fontSize: "20px", fontWeight: 700, color: "#f87171", marginBottom: "20px", display: "flex", alignItems: "center", gap: "10px" }}><Flame size={20} /> {content.painTitle}</h2>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                        {content.painPoints.map((pain, idx) => (
                            <div key={idx} style={{ background: '#0f172a', padding: '15px', borderRadius: '10px', border: '1px solid #334155' }}>
                                <div style={{ fontSize: '24px', marginBottom: '10px' }}>{pain.icon}</div>
                                <p style={{ margin: 0, fontSize: '14px', fontStyle: 'italic', color: '#cbd5e1' }}>{pain.text}</p>
                            </div>
                        ))}
                    </div>
                </div>

                {/* 4. LOGIC TRAP */}
                <div style={{ padding: "20px 10px", marginBottom: "30px" }}>
                    <h2 style={{ fontSize: "24px", fontWeight: 800, marginBottom: "20px", textAlign: "center", color: "#e2e8f0" }}>{content.logicTitle}</h2>
                    <div style={{ background: "rgba(220, 38, 38, 0.15)", padding: "25px", borderRadius: "15px", textAlign: "center", border: "1px dashed #ef4444", color: "#fca5a5" }}>
                        <p dangerouslySetInnerHTML={{ __html: content.logicDescription }} />
                    </div>
                </div>

                {/* 5. AGITATION (HIGHLIGHT) */}
                <div style={{ background: "linear-gradient(180deg, #1e293b 0%, #0f172a 100%)", color: "#f1f5f9", padding: "40px 25px", borderRadius: "25px", marginBottom: "30px", textAlign: "center", position: "relative", overflow: "hidden", border: "1px solid #334155", boxShadow: "0 10px 40px rgba(0,0,0,0.4)" }}>
                    <h2 style={{ fontSize: "22px", fontWeight: 800, marginBottom: "20px", color: "#fbbf24" }}>{content.agitationTitle}</h2>
                    {content.agitationText.map((text, idx) => (
                        <p key={idx} style={{ fontSize: "15px", lineHeight: 1.8, marginBottom: "20px", color: "#cbd5e1" }} dangerouslySetInnerHTML={{ __html: text }} />
                    ))}
                    <div style={{ background: "rgba(0, 0, 0, 0.3)", padding: "20px", borderRadius: "10px", marginBottom: "25px", border: "1px solid #475569" }}>
                        {content.agitationBullets.map((bullet, idx) => (
                            <p key={idx} style={{ margin: idx === 1 ? "15px 0" : "0", color: "#cbd5e1", fontSize: "15px" }}>{bullet.trigger} 👉 <strong style={{color: "#f87171"}}>{bullet.result}</strong></p>
                        ))}
                    </div>
                    <p style={{ fontWeight: "bold", fontSize: "16px", color: "#ffffff", letterSpacing: "0.5px" }}>{content.agitationClosing}</p>
                </div>

                {/* 6. SOLUTION */}
                <div style={{ background: "#1e293b", padding: "30px 25px", borderRadius: "25px", marginBottom: "30px", boxShadow: "0 10px 30px rgba(0,0,0,0.3)", border: "1px solid #334155" }}>
                    <h2 style={{ fontSize: "22px", fontWeight: 700, color: "#fbbf24", marginBottom: "20px", textAlign: "center", textTransform: "uppercase", letterSpacing: "1px" }}>{content.shiftTitle}</h2>
                    <p style={{ marginBottom: "20px", textAlign: "center", color: "#cbd5e1" }} dangerouslySetInnerHTML={{ __html: content.shiftDescription }} />
                    <div style={{ padding: "20px", background: "rgba(16, 185, 129, 0.05)", borderRadius: "15px", border: "1px solid rgba(16, 185, 129, 0.2)", marginBottom: "20px" }}>
                        <p style={{ fontWeight: "bold", color: "#34d399", marginBottom: "15px", textAlign: "center" }}>✨ MANIFESTASI TAHTA ANDA:</p>
                        <ul style={{ listStyle: "none", padding: 0 }}>
                            {content.shiftResults.map((res, idx) => (
                                <li key={idx} style={{ padding: "10px 0", borderBottom: idx !== 2 ? "1px dashed rgba(52, 211, 153, 0.2)" : "none", color: "#e2e8f0" }} dangerouslySetInnerHTML={{ __html: res }} />
                            ))}
                        </ul>
                    </div>
                </div>

                {/* 7. AUTHORITY */}
                <div style={{ background: "#0f172a", padding: "30px 20px", borderRadius: "25px", marginBottom: "30px", border: "1px solid #334155", boxShadow: "0 5px 15px rgba(0,0,0,0.2)" }}>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '15px', marginBottom: '20px', alignItems: 'center' }}>
                        <img src={founderImages[0]} alt="eL Reyzandra" style={{ width: '100%', borderRadius: '15px', objectFit: 'cover', aspectRatio: '9/16', filter: "grayscale(20%) contrast(110%)" }} />
                        <img src={founderImages[1]} alt="eL Reyzandra" style={{ width: '100%', borderRadius: '15px', objectFit: 'cover', aspectRatio: '1/1', filter: "grayscale(20%) contrast(110%)" }} />
                    </div>
                    <div style={{ textAlign: "center", marginBottom: "20px" }}>
                        <h2 style={{ fontSize: "22px", fontWeight: 800, color: "#fbbf24", marginBottom: "5px" }}>Siapa eL Reyzandra?</h2>
                        <div style={{ fontSize: "13px", color: "#94a3b8", letterSpacing: "2px", textTransform: "uppercase" }}>The Mind Engineer</div>
                    </div>
                    <p style={{ fontSize: "15px", lineHeight: 1.7, marginBottom: "15px", color: "#cbd5e1", textAlign: "center" }}>Selama 16 tahun, saya meneliti bagaimana <strong>Alam Bawah Sadar</strong> mengendalikan 95% hidup manusia. Saya bukan motivator. Saya adalah "Insinyur Pikiran".</p>
                    <div style={{ background: "rgba(251, 191, 36, 0.1)", color: "#fbbf24", padding: "10px", borderRadius: "8px", textAlign: "center", fontSize: "14px", fontWeight: "bold", border: "1px solid #b45309" }}>"Bahagia Adalah Koentji"</div>
                </div>

                {/* 8. VIDEO TESTIMONIALS */}
                <div style={{ marginBottom: "40px" }}>
                    <h2 style={{ fontSize: "20px", fontWeight: 800, marginBottom: "20px", textAlign: "center", color: "#f1f5f9" }}>Bukti Nyata (Tanpa Rekayasa)</h2>
                    <div style={{ display: "flex", overflowX: "auto", gap: "15px", paddingBottom: "15px", scrollSnapType: "x mandatory" }}>
                        {videoTestimonials.map((testi, idx) => (
                            <div key={idx} style={{ minWidth: "260px", background: "#1e293b", borderRadius: "15px", padding: "15px", scrollSnapAlign: "center", boxShadow: "0 4px 15px rgba(0,0,0,0.2)", border: "1px solid #334155" }}>
                                <video controls poster={testi.poster} style={{ width: "100%", borderRadius: "10px", aspectRatio: "9/16", objectFit: "cover", marginBottom: "10px", backgroundColor: "#020617" }}>
                                    <source src={testi.videoUrl} type="video/mp4" />
                                </video>
                                <div style={{ fontWeight: "bold", fontSize: "14px", color: "#fbbf24" }}>{testi.name}</div>
                                <div style={{ fontSize: "12px", color: "#94a3b8" }}>{testi.title}</div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* 9. TEXT TESTIMONIALS */}
                <div style={{ background: "#1e293b", padding: "30px 20px", borderRadius: "25px", marginBottom: "30px", border: "1px solid #334155", boxShadow: "0 5px 15px rgba(0,0,0,0.2)" }}>
                     <h2 style={{ fontSize: "20px", fontWeight: 800, marginBottom: "20px", textAlign: "center", color: "#f1f5f9" }}>Suara Mereka Yang Sudah Bangkit</h2>
                     {testimonials.map((testi, idx) => (
                        <div key={idx} style={{ background: "#0f172a", padding: "20px", borderRadius: "10px", marginBottom: "15px", border: "1px solid #334155" }}>
                            <div style={{ fontWeight: 700, color: "#fbbf24", marginBottom: "5px" }}>{testi.name} {testi.verified && <span style={{color: '#34d399'}}>✓</span>}</div>
                            <div style={{ fontSize: '12px', color: '#64748b', marginBottom: '10px' }}>{testi.title}</div>
                            <p style={{ fontSize: "14px", lineHeight: 1.7, fontStyle: "italic", color: "#cbd5e1" }}>"{testi.text}"</p>
                        </div>
                     ))}
                </div>

                {/* 10. CURRICULUM */}
                <div style={{ background: "#1e293b", padding: "30px 25px", borderRadius: "25px", marginBottom: "30px", border: "1px solid #b45309", boxShadow: "0 0 20px rgba(180, 83, 9, 0.2)" }}>
                    <div style={{ background: "#b45309", color: "#fff", display: "inline-block", padding: "5px 15px", borderRadius: "20px", fontSize: "12px", fontWeight: "bold", marginBottom: "15px" }}>MATERI EKSKLUSIF</div>
                    <h2 style={{ fontSize: "22px", fontWeight: 800, marginBottom: "25px", color: "#ffffff" }}>{content.webinarTitle}</h2>
                    <div style={{ marginBottom: "20px" }}>
                        {content.curriculum.map((item, idx) => (
                            <div key={idx} style={{ display: "flex", gap: "15px", marginBottom: "20px" }}>
                                <div style={{ background: "rgba(251, 191, 36, 0.1)", color: "#fbbf24", width: "35px", height: "35px", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold", flexShrink: 0, border: "1px solid #fbbf24" }}>{idx + 1}</div>
                                <div>
                                    <strong style={{ color: "#fbbf24", fontSize: "16px" }}>{item.title}</strong>
                                    <p style={{ fontSize: "14px", margin: "5px 0 0 0", color: "#cbd5e1" }}>{item.desc}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* 11. STEP BY STEP GUIDE */}
                <div style={{ padding: "30px 10px", marginBottom: "30px" }}>
                    <h2 style={{ fontSize: "22px", fontWeight: 800, marginBottom: "30px", color: "#e2e8f0", textAlign: "center" }}>Jalan Pulang Menuju Tahta</h2>
                    <div style={{ position: "relative" }}>
                        {/* Connecting Line */}
                        <div style={{ position: "absolute", left: "20px", top: "20px", bottom: "20px", width: "2px", background: "#334155" }}></div>
                        
                        {content.steps.map((step, idx) => (
                            <div key={idx} style={{ display: "flex", gap: "20px", marginBottom: "30px", position: "relative" }}>
                                <div style={{ width: "40px", height: "40px", borderRadius: "50%", background: "#b45309", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold", flexShrink: 0, zIndex: 2, border: "4px solid #0f172a" }}>{idx + 1}</div>
                                <div>
                                    <h3 style={{ color: "#fbbf24", fontSize: "18px", fontWeight: "bold", marginBottom: "5px" }}>{step.title}</h3>
                                    <p style={{ color: "#94a3b8", fontSize: "14px" }}>{step.desc}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* 12. PRICING & PAYMENT FORM */}
                <div style={{ background: "#1e293b", color: "#f1f5f9", padding: "40px 25px", borderRadius: "30px", marginBottom: "40px", boxShadow: "0 20px 50px rgba(0,0,0,0.4)", border: "1px solid #334155" }}>
                    <div style={{ textAlign: "center" }}>
                        <h2 style={{ marginTop: "10px", fontSize: "22px", fontWeight: 700, marginBottom: "20px", color: "#f8fafc" }}>Investasi Harga Diri</h2>
                        <p style={{ fontSize: "14px", color: "#94a3b8", marginBottom: "20px" }}>Harga normal sesi private:</p>
                        <div style={{ fontSize: "20px", textDecoration: "line-through", color: "#64748b", marginBottom: "5px" }}>{content.priceAnchor}</div>
                        <div style={{ fontSize: "42px", fontWeight: 900, color: "#fbbf24", marginBottom: "10px", textShadow: "0 0 20px rgba(251, 191, 36, 0.3)" }}>{content.priceReal}</div>
                        <p style={{ fontSize: "13px", color: "#94a3b8", marginBottom: "30px" }}>(Lebih murah dari traktir teman makan)</p>
                    </div>

                    {/* FORM INPUTS */}
                    <div className="space-y-6 mt-8">
                        <div className="space-y-4">
                            <h3 className="font-bold text-lg flex items-center gap-2 text-amber-500">
                                <User className="w-5 h-5" /> Identitas Calon Raja
                            </h3>
                            <div className="grid gap-4">
                                <div>
                                    <Label htmlFor="name" className="text-slate-400 font-semibold mb-1 block">Nama Lengkap</Label>
                                    <Input 
                                        id="name" 
                                        autoComplete="name"
                                        placeholder="Nama Anda" 
                                        value={userName} 
                                        onChange={(e) => setUserName(e.target.value)} 
                                        className="bg-slate-800 text-white placeholder:text-slate-500 border-slate-600 focus:border-amber-500 h-12"
                                    />
                                </div>
                                <div className="grid md:grid-cols-2 gap-4">
                                    <div>
                                        <Label htmlFor="email" className="text-slate-400 font-semibold mb-1 block">Email (Wajib Aktif)</Label>
                                        <Input 
                                            id="email" 
                                            type="email" 
                                            autoComplete="email"
                                            placeholder="Link dikirim kesini" 
                                            value={userEmail} 
                                            onChange={(e) => setUserEmail(e.target.value)} 
                                            className="bg-slate-800 text-white placeholder:text-slate-500 border-slate-600 focus:border-amber-500 h-12"
                                        />
                                    </div>
                                    <div>
                                        <Label htmlFor="phone" className="text-slate-400 font-semibold mb-1 block">WhatsApp</Label>
                                        <Input 
                                            id="phone" 
                                            type="tel" 
                                            autoComplete="tel"
                                            placeholder="0812xxxx" 
                                            value={phoneNumber} 
                                            onChange={(e) => setPhoneNumber(e.target.value)} 
                                            className="bg-slate-800 text-white placeholder:text-slate-500 border-slate-600 focus:border-amber-500 h-12"
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="space-y-4">
                            <h3 className="font-bold text-lg flex items-center gap-2 text-amber-500">
                                <CreditCard className="w-5 h-5" /> Metode Pembayaran
                            </h3>
                            <RadioGroup value={selectedPaymentMethod} onValueChange={setSelectedPaymentMethod} className="grid grid-cols-1 gap-4">
                                {paymentMethods.map((method) => (
                                    <Label key={method.code} className={`flex items-start p-4 border rounded-xl cursor-pointer transition-all ${selectedPaymentMethod === method.code ? 'border-amber-500 bg-amber-950/30 shadow-md ring-1 ring-amber-500' : 'border-slate-700 bg-slate-800 hover:border-slate-500'}`}>
                                        <RadioGroupItem value={method.code} id={method.code} className="mt-1 mr-4 border-slate-400 text-amber-500" />
                                        <div className="flex-1">
                                            <div className="font-bold text-slate-100 text-lg">{method.name}</div>
                                            <div className="text-sm text-slate-400">{method.description}</div>
                                        </div>
                                    </Label>
                                ))}
                            </RadioGroup>
                        </div>

                        <Button 
                            size="lg" 
                            className="w-full text-lg py-8 bg-gradient-to-r from-amber-600 to-red-700 hover:from-amber-700 hover:to-red-800 font-bold shadow-xl transition-all hover:scale-[1.01] active:scale-[0.99] text-white border-none mt-6 shadow-amber-900/50"
                            onClick={handleCreatePayment}
                            disabled={loading}
                        >
                            {loading ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Memproses...</> : content.ctaButton}
                        </Button>
                        
                         <div className="flex items-center justify-center gap-4 text-xs text-slate-500 font-medium mt-4">
                            <div className="flex items-center gap-1">
                                <ShieldCheck className="w-3 h-3 text-green-500" /> Secure Payment
                            </div>
                            <div className="flex items-center gap-1">
                                <CheckCircle className="w-3 h-3 text-blue-500" /> Instant Access
                            </div>
                        </div>
                    </div>
                </div>

                {/* 13. FAQ SECTION */}
                <div style={{ marginBottom: "40px", padding: "0 10px" }}>
                    <h2 style={{ fontSize: "22px", fontWeight: 800, marginBottom: "25px", color: "#f1f5f9", textAlign: "center" }}>Pertanyaan Sering Diajukan</h2>
                    <div style={{ display: "flex", flexDirection: "column", gap: "15px" }}>
                        {content.faq.map((item, idx) => (
                            <div key={idx} style={{ background: "#1e293b", padding: "20px", borderRadius: "15px", border: "1px solid #334155", boxShadow: "0 5px 15px rgba(0,0,0,0.2)" }}>
                                <div style={{ color: "#fbbf24", fontWeight: "bold", marginBottom: "10px", fontSize: "16px" }}>{item.q}</div>
                                <div style={{ color: "#cbd5e1", fontSize: "14px", lineHeight: 1.6 }}>{item.a}</div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* FOOTER */}
                <div style={{ textAlign: "center", paddingBottom: "30px", color: "#64748b", fontSize: "12px", background: "transparent" }}>
                    <p style={{ marginBottom: "5px", fontWeight: "bold", color: "#94a3b8" }}>eL Vision Group</p>
                    <p style={{ color: "#64748b" }}>"Bahagia Adalah Koentji"</p>
                </div>
            </div>
        </div>
    );
};

export default WebinarPriaSusis;