import { useEffect, useRef, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { 
  initFacebookPixelWithLogging, 
  trackPageViewEvent, 
  trackViewContentEvent, 
  AdvancedMatchingData,
  getFbcFbpCookies,
  waitForFbp
} from '@/utils/fbpixel';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { useToast } from '@/hooks/use-toast';
import { Toaster } from '@/components/ui/toaster';
import { Card, CardContent } from '@/components/ui/card';
import { ArrowLeft, Copy, CreditCard, User, CheckCircle, ShieldCheck, Loader2 } from 'lucide-react';

const WebinarIbu = () => {
    const { toast } = useToast();
    const hasFiredPixelsRef = useRef(false);
    const sentEventIdsRef = useRef(new Set<string>());
    const addPaymentInfoFiredRef = useRef(false);
    const purchaseFiredRef = useRef(false);
    const isProcessingRef = useRef(false);

    // Form State
    const [userName, setUserName] = useState('');
    const [userEmail, setUserEmail] = useState('');
    const [phoneNumber, setPhoneNumber] = useState('');
    const [selectedPaymentMethod, setSelectedPaymentMethod] = useState('QRIS');
    const [loading, setLoading] = useState(false);
    const [paymentData, setPaymentData] = useState<any>(null);
    const [showPaymentInstructions, setShowPaymentInstructions] = useState(false);
    
    // Hardcoded for this specific webinar
    const productNameBackend = 'webinar_cinta_sadar'; 
    const displayProductName = 'Webinar Stop Menarik Pria Toxic';
    const productPrice = 200000;
    const pixelId = '3319324491540889'; // Same as ebook_feminine

    const paymentMethods = [
        { code: 'QRIS', name: 'QRIS', description: 'Scan pakai GoPay, OVO, Dana, ShopeePay, BCA Mobile, dll' },
        { code: 'BCAVA', name: 'BCA Virtual Account', description: 'Transfer otomatis via BCA' },
        { code: 'BNIVA', name: 'BNI Virtual Account', description: 'Transfer otomatis via BNI' },
        { code: 'BRIVA', name: 'BRI Virtual Account', description: 'Transfer otomatis via BRI' },
        { code: 'MANDIRIVA', name: 'Mandiri Virtual Account', description: 'Transfer otomatis via Mandiri' },
        { code: 'PERMATAVA', name: 'Permata Virtual Account', description: 'Transfer otomatis via Permata' },
    ];

    const formatCurrency = (amount: number) => {
        return new Intl.NumberFormat('id-ID', {
            style: 'currency',
            currency: 'IDR',
            minimumFractionDigits: 0,
            maximumFractionDigits: 0,
        }).format(amount);
    };

    const copyToClipboard = (text: string) => {
        navigator.clipboard.writeText(text);
        toast({
            title: "Berhasil Disalin",
            description: "Teks telah disalin ke clipboard",
        });
    };

    // Helper to send CAPI events
    const sendCapiEvent = async (eventName: string, eventData: any, eventId?: string) => {    
      try {
        // 🛡️ DEDUPLICATION CHECK
        if (eventId && sentEventIdsRef.current.has(eventId)) {
          console.warn(`⚠️ Duplicate CAPI Event Blocked: ${eventName} (ID: ${eventId})`);
          return;
        }
        if (eventId) {
          sentEventIdsRef.current.add(eventId);
        }

        // ⏳ Wait for FBP to be generated by the browser pixel before sending CAPI
        await waitForFbp();

        const { data: { session } } = await supabase.auth.getSession();
        const body: any = {
          pixelId,
          eventName,
          customData: eventData,
          eventId: eventId,
          eventSourceUrl: window.location.href,
          testCode: 'TEST33364'
        };

        // Get FBC and FBP from cookies using the utility function
        const { fbc, fbp } = getFbcFbpCookies();

        const userData: any = {
          client_user_agent: navigator.userAgent,
        };

        // Prioritize form input email/phone/name, then authenticated user email/phone/name
        let rawName = userName;
        if (userEmail) {
            userData.email = userEmail;
        } else if (session?.user?.email) {
            userData.email = session.user.email;
        }
        
        if (phoneNumber) {
            userData.phone = phoneNumber;
        } else if (session?.user?.user_metadata?.phone) {
            userData.phone = session.user.user_metadata.phone;
        }
        
        if (!rawName && session?.user?.user_metadata?.full_name) {
            rawName = session.user.user_metadata.full_name;
        }

        if (rawName) {
            const nameParts = rawName.trim().split(/\s+/);
            userData.fn = nameParts[0];
            if (nameParts.length > 1) {
                userData.ln = nameParts.slice(1).join(' ');
            }
        }

        // External ID from authenticated user (Supabase user ID)
        if (session?.user?.id) {
          userData.external_id = session.user.id;
        }

        // 🎯 FACEBOOK LOGIN ID EXTRACTION
        const fbIdentity = session?.user?.identities?.find(id => id.provider === 'facebook');
        if (fbIdentity) {
          userData.db_id = fbIdentity.id;
        }

        if (fbc) userData.fbc = fbc;
        if (fbp) userData.fbp = fbp;
        
        body.userData = userData;

        console.log(`🚀 Sending CAPI Event: ${eventName}`, body);

        const { data, error } = await supabase.functions.invoke('capi-universal', { body });
        
        if (error) {
          console.error(`❌ CAPI Error for ${eventName}:`, error);
          throw error;
        }
        
        console.log(`✅ CAPI Success for ${eventName}:`, data);
      } catch (error) {
        console.error(`❌ Failed to send CAPI event ${eventName}:`, error);
        throw error;
      }
    };

    const handlePixelAndCapiEvents = async (viewOnly: boolean = false) => {
      if (hasFiredPixelsRef.current) {
        console.warn("⚠️ Duplicate call to handlePixelAndCapiEvents blocked by ref check.");
        return;
      }
      hasFiredPixelsRef.current = true;
    
      try {
        const advancedMatching: AdvancedMatchingData = {};
        if (userEmail) advancedMatching.em = userEmail;
        if (phoneNumber) advancedMatching.ph = phoneNumber;
    
        const nameParts = userName.trim().split(/\s+/);
        if (nameParts.length > 0) advancedMatching.fn = nameParts[0];
        if (nameParts.length > 1) advancedMatching.ln = nameParts.slice(1).join(' ');
    
        console.log("🎬 Initializing Facebook Pixel with Advanced Matching...");
        initFacebookPixelWithLogging(pixelId, advancedMatching);
    
        console.log("📄 Tracking PageView...");
        trackPageViewEvent();
    
        console.log("🔍 Tracking ViewContent...");
        const viewContentEventId = `view_content_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
        trackViewContentEvent({
          content_name: displayProductName,
          content_ids: [productNameBackend],
          content_type: 'product',
          value: productPrice,
          currency: 'IDR'
        }, viewContentEventId);
    
        await sendCapiEvent('ViewContent', {
          content_name: displayProductName,
          content_ids: [productNameBackend],
          content_type: 'product',
          value: productPrice,
          currency: 'IDR'
        }, viewContentEventId);
    
        if (!viewOnly) {
          if (typeof window !== 'undefined' && (window as any).fbq) {
            console.log("💳 Tracking AddPaymentInfo (Browser Pixel)...");
            const addPaymentInfoEventId = `add_payment_info_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
            (window as any).fbq('track', 'AddPaymentInfo', {
              content_name: displayProductName,
              content_ids: [productNameBackend],
              value: productPrice,
              currency: 'IDR'
            }, { eventID: addPaymentInfoEventId });
            
            await sendCapiEvent('AddPaymentInfo', {
              content_name: displayProductName,
              content_ids: [productNameBackend],
              value: productPrice,
              currency: 'IDR'
            }, addPaymentInfoEventId);
          }
        }
      } catch (error) {
        console.error("❌ Error in handlePixelAndCapiEvents:", error);
      }
    };

    const handleCreatePayment = async () => {
      if (!userName || !userEmail || !phoneNumber) {
        toast({
          title: "Data Tidak Lengkap",
          description: "Mohon isi semua data diri Anda",
          variant: "destructive"
        });
        return;
      }

      if (isProcessingRef.current) {
        console.warn("⚠️ Payment already processing, ignoring duplicate click.");
        return;
      }

      isProcessingRef.current = true;
      setLoading(true);

      try {
        if (!hasFiredPixelsRef.current) {
          await handlePixelAndCapiEvents(false);
        } else if (!addPaymentInfoFiredRef.current) {
          if (typeof window !== 'undefined' && (window as any).fbq) {
            console.log("💳 Tracking AddPaymentInfo (Browser Pixel) - delayed...");
            const addPaymentInfoEventId = `add_payment_info_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
            (window as any).fbq('track', 'AddPaymentInfo', {
              content_name: displayProductName,
              content_ids: [productNameBackend],
              value: productPrice,
              currency: 'IDR'
            }, { eventID: addPaymentInfoEventId });
            
            await sendCapiEvent('AddPaymentInfo', {
              content_name: displayProductName,
              content_ids: [productNameBackend],
              value: productPrice,
              currency: 'IDR'
            }, addPaymentInfoEventId);
            addPaymentInfoFiredRef.current = true;
          }
        }

        const { data, error } = await supabase.functions.invoke('payment-create-xendit', {
          body: {
            product_name: productNameBackend,
            user_name: userName,
            user_email: userEmail,
            phone_number: phoneNumber,
            payment_method: selectedPaymentMethod,
          }
        });

        if (error) throw error;
        if (!data?.payment_url) throw new Error('Payment URL tidak diterima dari server');

        console.log("💳 Payment created successfully:", data);
        setPaymentData(data);
        setShowPaymentInstructions(true);

        window.scrollTo({ top: 0, behavior: 'smooth' });

      } catch (error: any) {
        console.error("❌ Payment creation failed:", error);
        toast({
          title: "Gagal Membuat Pembayaran",
          description: error.message || "Terjadi kesalahan saat memproses pembayaran",
          variant: "destructive"
        });
      } finally {
        setLoading(false);
        isProcessingRef.current = false;
      }
    };

    const pollPaymentStatus = async (invoiceId: string) => {
      const maxAttempts = 60;
      let attempts = 0;

      const poll = async () => {
        if (attempts >= maxAttempts) {
          console.log("⏱️ Polling timeout reached");
          return;
        }

        try {
          const { data, error } = await supabase.functions.invoke('payment-status-xendit', {
            body: { invoice_id: invoiceId }
          });

          if (error) throw error;

          console.log(`🔄 Polling attempt ${attempts + 1}:`, data);

          if (data?.status === 'PAID' || data?.status === 'SETTLED') {
            console.log("✅ Payment confirmed as PAID/SETTLED");
            
            if (!purchaseFiredRef.current && typeof window !== 'undefined' && (window as any).fbq) {
              console.log("🎉 Tracking Purchase (Browser Pixel)...");
              const purchaseEventId = `purchase_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
              (window as any).fbq('track', 'Purchase', {
                content_name: displayProductName,
                content_ids: [productNameBackend],
                value: productPrice,
                currency: 'IDR'
              }, { eventID: purchaseEventId });

              await sendCapiEvent('Purchase', {
                content_name: displayProductName,
                content_ids: [productNameBackend],
                value: productPrice,
                currency: 'IDR'
              }, purchaseEventId);
              
              purchaseFiredRef.current = true;
            }

            toast({
              title: "Pembayaran Berhasil! 🎉",
              description: "Terima kasih! Link webinar akan dikirim ke email Anda.",
            });

            setTimeout(() => {
              window.location.href = '/success';
            }, 2000);
            
            return;
          }

          attempts++;
          setTimeout(poll, 5000);
        } catch (error) {
          console.error("❌ Error polling payment status:", error);
          attempts++;
          setTimeout(poll, 5000);
        }
      };

      poll();
    };

    useEffect(() => {
      if (!hasFiredPixelsRef.current) {
        handlePixelAndCapiEvents(true);
      }
    }, []);

    useEffect(() => {
      if (paymentData?.invoice_id) {
        console.log("🔄 Starting payment status polling for:", paymentData.invoice_id);
        pollPaymentStatus(paymentData.invoice_id);
      }
    }, [paymentData]);

    // CONTENT OBJECT - UPDATED FOR CINTA SADAR AVATAR
    const content = {
        badge: "KHUSUS PEREMPUAN YANG CAPEK DISAKITI & DIMANFAATKAN",
        headline: "Cantik, Pinter, Tapi Kok Selalu Jatuh ke Pelukan 'Buaya'?",
        subheadline: "Kamu pikir kali ini beda karena dia manis di awal. Tapi akhirnya sama saja: Manipulatif, selingkuh, atau ghosting.",
        eventDate: "Live Zoom - Sabtu, 22 Februari 2025, 17:00 WIB",
        
        painTitle: "Jujur, Kamu Mulai Mikir Begini Kan?",
        painPoints: [
            {
                icon: "💔",
                text: "\"Apa ada yang salah sama gue? Apa gue dikutuk selalu dapet cowok toxic?\""
            },
            {
                icon: "😩",
                text: "\"Jujur, gue capek harus mulai PDKT dari nol lagi cuma buat dibuang di tengah jalan.\""
            },
            {
                icon: "🤡",
                text: "\"Gue udah kasih segalanya, tenaga, waktu, bahkan uang... tapi ujungnya dikhianatin.\""
            }
        ],

        logicTitle: "Perangkap Bawah Sadarmu",
        logicDescription: "<strong>KAMU MENARIK APA YANG KAMU RASA:</strong><br/>Bukan karena kamu kurang cantik, tapi karena bawah sadarmu merasa 'tidak berharga'. Inilah yang membuat radar cintamu justru mencari pria yang akan merendahkanmu.",

        agitationTitle: "🐍 THE TOXIC ATTRACTION CYCLE",
        agitationText: [
            "Trauma diselingkuhi atau ditinggalkan bukan sekadar nasib buruk. Itu adalah pola energi.",
            "Tanpa disadari, pikiranmu seperti <strong>magnet bagi pria bermasalah</strong>:"
        ],
        agitationBullets: [
            { trigger: "Merasa 'I am not worthy'", result: "Menarik cowok narsis yang butuh pelayan" },
            { trigger: "Takut kesepian", result: "Menarik cowok ghosting yang datang saat butuh saja" },
            { trigger: "Trauma masa lalu", result: "Terjebak di hubungan yang polanya itu-itu saja" }
        ],
        agitationClosing: "Jika polanya tidak diputus sekarang, kamu hanya akan berganti wajah pria dengan rasa sakit yang sama.",

        shiftTitle: "✨ Bayangkan Jika...",
        shiftDescription: "Kamu memiliki <strong>Standard & Aura</strong> yang begitu kuat sehingga pria toxic minder mendekat, dan pria berkualitas berjuang untukmu.",
        shiftResults: [
            "💃 Kamu merasa utuh dan bahagia meski tanpa pasangan (Aura Magnetis)",
            "🛡️ Radar 'Red Flag' kamu aktif otomatis sebelum terlambat",
            "👑 Menarik pria yang benar-benar menghargai dan memuliakanmu"
        ],

        webinarTitle: "Apa yang Akan Kita Bongkar:",
        curriculum: [
            { title: "Detoks Bawah Sadar", desc: "Buang program 'Gue Gak Layak Bahagia' dalam 1 sesi singkat." },
            { title: "Aura Queen Mechanism", desc: "Cara memancarkan energi feminin yang bikin pria berinvestasi emosi." },
            { title: "Psychological Red Flag", desc: "Teknik membaca niat pria hanya dari 30 menit percakapan pertama." }
        ],

        steps: [
            { title: "Amankan Slot Webinar", desc: "Pilih metode pembayaran untuk konfirmasi kehadiranmu." },
            { title: "Verifikasi Pembayaran", desc: "Proses otomatis, tidak perlu kirim bukti transfer secara manual." },
            { title: "Dapatkan Akses Kelas", desc: "Link Zoom dan materi akan langsung dikirim ke email kamu." }
        ],

        priceAnchor: "Rp 5.000.000",
        priceReal: "Rp 200.000",
        ctaButton: "🎯 DAFTAR WEBINAR: STOP MENARIK PRIA TOXIC",

        faq: [
            {
                q: "Apakah ini semacam konsultasi jodoh?",
                a: "Bukan. Ini adalah 'Mind Engineering' untuk mengubah magnet dalam dirimu agar tidak lagi menarik orang yang salah."
            },
            {
                q: "Saya baru putus dan masih trauma, apa boleh ikut?",
                a: "Justru ini saat terbaik. Sebelum kamu masuk ke hubungan baru, kita bersihkan dulu sampahnya agar tidak terulang."
            },
            {
                q: "Kalau saya tidak bisa hadir saat live?",
                a: "Tenang, rekaman eksklusif akan diberikan agar kamu bisa pelajari tekniknya berkali-kali."
            }
        ]
    };

    // ==========================================
    // 🖼️ MEDIA ASSETS (CONSTANTS)
    // ==========================================
    const founderImages = [
        "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/siapael/siapael1.jpeg",
        "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/siapael/siapael2.jpeg"
    ];

    const videoTestimonials = [
        { name: "Agus Mulyadi, SH., MH.", title: "Kepala Intelijen Pangandaran", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/AGUS_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/agus.jpg", thumbnail: "🎖️" },
        { name: "Dr. Gumilar", title: "Hipnoterapist & Pemimpin Yayasan", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/DRVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/dr.jpg", thumbnail: "⚕️" },
        { name: "Habib Umar", title: "Pemimpin Pondok Pesantren Atsaqofah", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/HABIBVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/habib.jpg", thumbnail: "🕌" },
        { name: "Umi Jamilah", title: "Pemimpin Yayasan", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/UMIVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/umi.jpg", thumbnail: "👳‍♀️" },
        { name: "Felicia", title: "Pengusaha", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/FELVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/felicia.jpg", thumbnail: "👩‍💼" },
        { name: "Lena", title: "Klien eL Vision", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/LENA_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/lena.jpg", thumbnail: "🌟" },
        { name: "Vio", title: "Klien eL Vision", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/VIOVIDEO_WA.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/vio2.jpg", thumbnail: "✨" },
        { name: "Arif", title: "Klien eL Vision", videoUrl: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/arif_inte.mp4", poster: "https://nlrgdhpmsittuwiiindq.supabase.co/storage/v1/object/public/testi/arif_inte.jpg", thumbnail: "👨‍💻" }
    ];

    const testimonials = [
        { name: "Siska", title: "Karyawan Swasta", image: "💎", rating: 5, text: "Gue selalu ngerasa 'gak pantes' dapet cowok baik. Setelah kelas eL Vision, gue berani nge-cut cowok manipulatif dalam sehari. Mind blowing!" },
        { name: "Indah", title: "Freelancer", image: "🎯", rating: 5, text: "Aura gue berubah total. Dulu selalu gue yang ngejar-ngejar, sekarang gue yang dikejar pria yang jauh lebih berkualitas." },
        { name: "Umi Jamilah", title: "Pemimpin Yayasan", verified: true, image: "👳‍♀️", rating: 5, text: "Manajemen energi yang diajarkan eL sangat aplikatif untuk membersihkan beban emosional masa lalu." },
        { name: "Felicia Quincy", title: "Pengusaha", verified: true, image: "👩‍💼", rating: 5, text: "Dulu keputusan gue selalu kabur karena trauma. Sekarang gue punya standar yang sangat jelas." },
        { name: "Lena", title: "Klien eL Vision", verified: true, image: "🌟", rating: 5, text: "Gue nemuin ketenangan yang selama ini hilang. Ternyata kuncinya ada di bawah sadar gue sendiri." },
        { name: "Putri", title: "Mahasiswi", image: "👩‍💼", rating: 5, text: "Gak perlu pakai susuk atau klenik. Ini murni psikologi dan reset otak. Berhasil banget!" },
        { name: "Vio", title: "Klien eL Vision", verified: true, image: "✨", rating: 5, text: "Program ini mengubah cara gue memandang diri sendiri. Gue bukan lagi 'korban' cinta." },
        { name: "Ratna", title: "Educator", image: "📚", rating: 5, text: "Sangat direkomendasikan buat cewek-cewek yang sering di-ghosting. Bongkar akarnya di sini." }
    ];

    if (showPaymentInstructions && paymentData) {
        return (
            <div style={{ minHeight: "100vh", background: "linear-gradient(135deg, #fce7f3 0%, #f3e7fc 100%)", padding: "20px 0" }}>
                <Toaster />
                <div style={{ maxWidth: "600px", margin: "0 auto", background: "white", borderRadius: "25px", padding: "30px 20px", boxShadow: "0 20px 60px rgba(236, 72, 153, 0.15)" }}>
                    <Button
                        variant="ghost"
                        onClick={() => setShowPaymentInstructions(false)}
                        className="mb-4 text-pink-600 hover:text-pink-700 hover:bg-pink-50"
                    >
                        <ArrowLeft className="mr-2 h-4 w-4" /> Kembali
                    </Button>

                    <div className="text-center mb-6">
                        <div className="w-20 h-20 bg-gradient-to-br from-pink-500 to-purple-500 rounded-full mx-auto mb-4 flex items-center justify-center">
                            <CheckCircle className="w-10 h-10 text-white" />
                        </div>
                        <h1 className="text-2xl font-bold text-slate-800 mb-2">Pesanan Berhasil Dibuat!</h1>
                        <p className="text-slate-600">Silakan selesaikan pembayaran kamu</p>
                    </div>

                    <Card className="mb-6 border-pink-200 shadow-lg">
                        <CardContent className="p-6">
                            <div className="space-y-4">
                                <div className="flex justify-between items-center pb-4 border-b border-pink-100">
                                    <span className="text-slate-600 font-semibold">Total Pembayaran</span>
                                    <span className="text-3xl font-bold text-pink-600">{formatCurrency(productPrice)}</span>
                                </div>

                                {selectedPaymentMethod === 'QRIS' ? (
                                    <div className="text-center py-4">
                                        <p className="text-sm text-slate-600 mb-4 font-semibold">Scan QR Code dengan aplikasi pembayaran kamu</p>
                                        {paymentData.qr_string && (
                                            <div className="bg-white p-4 rounded-xl inline-block border-2 border-pink-200 shadow-md">
                                                <img 
                                                    src={`https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encodeURIComponent(paymentData.qr_string)}`}
                                                    alt="QR Code"
                                                    className="w-64 h-64"
                                                />
                                            </div>
                                        )}
                                        <p className="text-xs text-slate-500 mt-4">Scan dengan GoPay, OVO, Dana, ShopeePay, atau m-banking lainnya</p>
                                    </div>
                                ) : (
                                    <div className="space-y-3">
                                        <div className="bg-pink-50 p-4 rounded-xl border border-pink-200">
                                            <Label className="text-sm text-slate-600 font-semibold mb-2 block">Nomor Virtual Account</Label>
                                            <div className="flex items-center gap-2">
                                                <code className="flex-1 bg-white px-4 py-3 rounded-lg text-lg font-bold text-slate-800 border border-pink-300">
                                                    {paymentData.virtual_account_number || paymentData.account_number}
                                                </code>
                                                <Button
                                                    size="sm"
                                                    variant="outline"
                                                    onClick={() => copyToClipboard(paymentData.virtual_account_number || paymentData.account_number)}
                                                    className="border-pink-300 text-pink-600 hover:bg-pink-50"
                                                >
                                                    <Copy className="h-4 w-4" />
                                                </Button>
                                            </div>
                                        </div>

                                        <div className="bg-purple-50 p-4 rounded-xl border border-purple-200">
                                            <Label className="text-sm text-slate-600 font-semibold mb-2 block">Jumlah Transfer</Label>
                                            <div className="flex items-center gap-2">
                                                <code className="flex-1 bg-white px-4 py-3 rounded-lg text-lg font-bold text-slate-800 border border-purple-300">
                                                    {formatCurrency(productPrice)}
                                                </code>
                                                <Button
                                                    size="sm"
                                                    variant="outline"
                                                    onClick={() => copyToClipboard(productPrice.toString())}
                                                    className="border-purple-300 text-purple-600 hover:bg-purple-50"
                                                >
                                                    <Copy className="h-4 w-4" />
                                                </Button>
                                            </div>
                                        </div>
                                    </div>
                                )}

                                <div className="bg-gradient-to-br from-pink-50 to-purple-50 p-4 rounded-xl border border-pink-200 mt-4">
                                    <p className="text-sm text-slate-700 leading-relaxed">
                                        <strong className="text-pink-600">📧 Link webinar akan dikirim otomatis ke email kamu</strong> setelah pembayaran dikonfirmasi.
                                        Mohon cek inbox atau folder spam.
                                    </p>
                                </div>

                                {paymentData.payment_url && (
                                    <Button
                                        className="w-full bg-gradient-to-r from-pink-600 to-purple-600 hover:from-pink-700 hover:to-purple-700 text-white font-bold py-6 mt-4 shadow-lg"
                                        onClick={() => window.open(paymentData.payment_url, '_blank')}
                                    >
                                        Buka Halaman Pembayaran
                                    </Button>
                                )}
                            </div>
                        </CardContent>
                    </Card>

                    <div className="text-center text-xs text-slate-500 mt-6">
                        <p>Pembayaran akan otomatis dikonfirmasi dalam 1-5 menit</p>
                        <p className="mt-1">Jika ada kendala, hubungi customer service kami</p>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div style={{
            fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif",
            background: "linear-gradient(135deg, #1e1b29 0%, #2d1b3d 100%)",
            color: "#e2e8f0",
            lineHeight: 1.6
        }}>
            <Toaster />
            <div style={{ maxWidth: "680px", margin: "0 auto", padding: "20px" }}>
                
                {/* 1. HEADER LOGO */}
                <div style={{ textAlign: "center", padding: "20px 0", marginBottom: "20px" }}>
                    <div style={{ fontSize: "24px", fontWeight: 800, color: "#ec4899", letterSpacing: "2px" }}>eL VISION</div>
                    <div style={{ fontSize: "12px", color: "#94a3b8", textTransform: "uppercase", letterSpacing: "1px" }}>Official Webinar Series</div>
                </div>

                {/* 2. HERO SECTION */}
                <div style={{ textAlign: "center", padding: "40px 20px", background: "rgba(30, 41, 59, 0.8)", borderRadius: "25px", marginBottom: "30px", boxShadow: "0 10px 30px rgba(0,0,0,0.3)", border: "1px solid rgba(236, 72, 153, 0.1)" }}>
                    <span style={{ background: "rgba(236, 72, 153, 0.1)", color: "#f9a8d4", padding: "10px 25px", borderRadius: "50px", fontSize: "16px", fontWeight: "900", marginBottom: "25px", display: "inline-block", letterSpacing: "1px", border: "1px solid #ec4899" }}>
                        {content.badge}
                    </span>
                    <h1 style={{ fontSize: "28px", fontWeight: 800, color: "#fff", marginBottom: "15px", lineHeight: 1.3 }}>{content.headline}</h1>
                    <p style={{ fontSize: "16px", color: "#cbd5e1", marginBottom: "0px", lineHeight: 1.6 }}>{content.subheadline}</p>
                    <div style={{ marginTop: "20px", background: "rgba(0,0,0,0.3)", display: "inline-block", padding: "8px 16px", borderRadius: "10px", border: "1px solid rgba(255,255,255,0.1)" }}>
                        🗓️ Event: <strong>{content.eventDate}</strong>
                    </div>
                </div>

                {/* 3. PAIN SECTION */}
                <div style={{ background: "#1e293b", padding: "30px 25px", borderRadius: "25px", marginBottom: "30px", borderLeft: "5px solid #ec4899" }}>
                    <h2 style={{ fontSize: "20px", fontWeight: 700, color: "#f9a8d4", marginBottom: "20px" }}>{content.painTitle}</h2>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                        {content.painPoints.map((pain, idx) => (
                            <div key={idx} style={{ background: 'rgba(255,255,255,0.05)', padding: '15px', borderRadius: '10px', border: '1px solid rgba(255,255,255,0.1)' }}>
                                <div style={{ fontSize: '24px', marginBottom: '10px' }}>{pain.icon}</div>
                                <p style={{ margin: 0, fontSize: '14px', fontStyle: 'italic', color: '#cbd5e1' }}>{pain.text}</p>
                            </div>
                        ))}
                    </div>
                </div>

                {/* 4. LOGIC TRAP */}
                <div style={{ padding: "20px 10px", marginBottom: "30px" }}>
                    <h2 style={{ fontSize: "24px", fontWeight: 800, marginBottom: "20px", textAlign: "center", color: "#fff" }}>{content.logicTitle}</h2>
                    <div style={{ background: "rgba(220, 38, 38, 0.1)", padding: "20px", borderRadius: "15px", textAlign: "center", border: "1px dashed #ef4444", color: "#fca5a5" }}>
                        <p dangerouslySetInnerHTML={{ __html: content.logicDescription }} />
                    </div>
                </div>

                {/* 5. AGITATION (HIGHLIGHT) */}
                <div style={{ background: "#020617", color: "white", padding: "40px 25px", borderRadius: "25px", marginBottom: "30px", textAlign: "center", position: "relative", overflow: "hidden", border: "1px solid #1e293b" }}>
                    <h2 style={{ fontSize: "22px", fontWeight: 800, marginBottom: "20px", color: "#f9a8d4" }}>{content.agitationTitle}</h2>
                    {content.agitationText.map((text, idx) => (
                        <p key={idx} style={{ fontSize: "15px", lineHeight: 1.8, marginBottom: "20px" }} dangerouslySetInnerHTML={{ __html: text }} />
                    ))}
                    <div style={{ background: "rgba(236, 72, 153, 0.05)", padding: "15px", borderRadius: "10px", marginBottom: "20px", border: "1px solid rgba(236, 72, 153, 0.1)" }}>
                        {content.agitationBullets.map((bullet, idx) => (
                            <p key={idx} style={{ margin: idx === 1 ? "10px 0" : "0", color: "#e2e8f0" }}>{bullet.trigger} 👉 <strong style={{color: "#f9a8d4"}}>{bullet.result}</strong></p>
                        ))}
                    </div>
                    <p style={{ fontWeight: "bold", fontSize: "16px", color: "#fff" }}>{content.agitationClosing}</p>
                </div>

                {/* 6. SOLUTION */}
                <div style={{ background: "#1e293b", padding: "30px 25px", borderRadius: "25px", marginBottom: "30px", boxShadow: "0 4px 20px rgba(0,0,0,0.2)" }}>
                    <h2 style={{ fontSize: "22px", fontWeight: 700, color: "#fff", marginBottom: "20px", textAlign: "center" }}>{content.shiftTitle}</h2>
                    <p style={{ marginBottom: "20px", textAlign: "center", color: "#cbd5e1" }} dangerouslySetInnerHTML={{ __html: content.shiftDescription }} />
                    <div style={{ padding: "15px", background: "rgba(236, 72, 153, 0.1)", borderRadius: "15px", border: "1px solid rgba(236, 72, 153, 0.3)", marginBottom: "20px" }}>
                        <p style={{ fontWeight: "bold", color: "#f9a8d4", marginBottom: "10px", textAlign: "center" }}>✨ SETELAH WEBINAR INI:</p>
                        <ul style={{ listStyle: "none", padding: 0 }}>
                            {content.shiftResults.map((res, idx) => (
                                <li key={idx} style={{ padding: "8px 0", borderBottom: idx !== 2 ? "1px dashed rgba(249, 168, 212, 0.3)" : "none", color: "#f9d5e5" }} dangerouslySetInnerHTML={{ __html: res }} />
                            ))}
                        </ul>
                    </div>
                </div>

                {/* 7. AUTHORITY */}
                <div style={{ background: "#1e293b", padding: "30px 20px", borderRadius: "25px", marginBottom: "30px", border: "1px solid #334155" }}>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '15px', marginBottom: '20px', alignItems: 'center' }}>
                        <img src={founderImages[0]} alt="eL Reyzandra" style={{ width: '100%', borderRadius: '15px', objectFit: 'cover', aspectRatio: '9/16' }} />
                        <img src={founderImages[1]} alt="eL Reyzandra" style={{ width: '100%', borderRadius: '15px', objectFit: 'cover', aspectRatio: '1/1' }} />
                    </div>
                    <div style={{ textAlign: "center", marginBottom: "20px" }}>
                        <h2 style={{ fontSize: "22px", fontWeight: 800, color: "#f9a8d4", marginBottom: "5px" }}>Siapa eL Reyzandra?</h2>
                        <div style={{ fontSize: "13px", color: "#94a3b8", letterSpacing: "1px", textTransform: "uppercase" }}>The Mind Engineer</div>
                    </div>
                    <p style={{ fontSize: "15px", lineHeight: 1.7, marginBottom: "15px", color: "#e2e8f0", textAlign: "center" }}>Selama 16 tahun, saya meneliti bagaimana <strong>Alam Bawah Sadar</strong> mengendalikan 95% hidup manusia. Saya bukan motivator. Saya adalah "Insinyur Pikiran".</p>
                    <div style={{ background: "#0f172a", color: "#f9a8d4", padding: "10px", borderRadius: "8px", textAlign: "center", fontSize: "14px", fontWeight: "bold", border: "1px solid #ec4899" }}>"Bahagia Adalah Koentji"</div>
                </div>

                {/* 8. VIDEO TESTIMONIALS */}
                <div style={{ marginBottom: "40px" }}>
                    <h2 style={{ fontSize: "20px", fontWeight: 800, marginBottom: "20px", textAlign: "center", color: "#fff" }}>Apa Kata Mereka?</h2>
                    <div style={{ display: "flex", overflowX: "auto", gap: "15px", paddingBottom: "15px", scrollSnapType: "x mandatory" }}>
                        {videoTestimonials.map((testi, idx) => (
                            <div key={idx} style={{ minWidth: "260px", background: "#1e293b", borderRadius: "15px", padding: "15px", scrollSnapAlign: "center", boxShadow: "0 2px 10px rgba(0,0,0,0.3)" }}>
                                <video controls poster={testi.poster} style={{ width: "100%", borderRadius: "10px", aspectRatio: "9/16", objectFit: "cover", marginBottom: "10px", backgroundColor: "#000" }}>
                                    <source src={testi.videoUrl} type="video/mp4" />
                                </video>
                                <div style={{ fontWeight: "bold", fontSize: "14px", color: "#f9a8d4" }}>{testi.name}</div>
                                <div style={{ fontSize: "12px", color: "#94a3b8" }}>{testi.title}</div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* 9. TEXT TESTIMONIALS */}
                <div style={{ background: "#1e293b", padding: "30px 20px", borderRadius: "25px", marginBottom: "30px", border: "1px solid #334155" }}>
                     <h2 style={{ fontSize: "20px", fontWeight: 800, marginBottom: "20px", textAlign: "center", color: "#fff" }}>Kisah Perubahan Nyata</h2>
                     {testimonials.map((testi, idx) => (
                        <div key={idx} style={{ background: "rgba(255,255,255,0.05)", padding: "20px", borderRadius: "10px", marginBottom: "15px" }}>
                            <div style={{ fontWeight: 700, color: "#f9a8d4", marginBottom: "5px" }}>{testi.name} {testi.verified && <span style={{color: '#34d399'}}>✓</span>}</div>
                            <div style={{ fontSize: '12px', color: '#94a3b8', marginBottom: '10px' }}>{testi.title}</div>
                            <p style={{ fontSize: "14px", lineHeight: 1.7, fontStyle: "italic", color: "#cbd5e1" }}>"{testi.text}"</p>
                        </div>
                     ))}
                </div>

                {/* 10. CURRICULUM - MATERI EKSKLUSIF */}
                <div style={{ background: "#1e293b", padding: "30px 25px", borderRadius: "25px", marginBottom: "30px", border: "2px solid #ec4899" }}>
                    <div style={{ background: "#ec4899", color: "#fff", display: "inline-block", padding: "5px 15px", borderRadius: "20px", fontSize: "12px", fontWeight: "bold", marginBottom: "15px" }}>MATERI EKSKLUSIF</div>
                    <h2 style={{ fontSize: "22px", fontWeight: 800, marginBottom: "25px", color: "#fff" }}>{content.webinarTitle}</h2>
                    <div style={{ marginBottom: "20px" }}>
                        {content.curriculum.map((item, idx) => (
                            <div key={idx} style={{ display: "flex", gap: "15px", marginBottom: "15px" }}>
                                <div style={{ background: "rgba(236, 72, 153, 0.1)", color: "#f9a8d4", width: "30px", height: "30px", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold", flexShrink: 0, border: "1px solid #ec4899" }}>{idx + 1}</div>
                                <div>
                                    <strong style={{ color: "#f9a8d4" }}>{item.title}</strong>
                                    <p style={{ fontSize: "14px", margin: "5px 0 0 0", color: "#cbd5e1" }}>{item.desc}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* 11. STEP BY STEP GUIDE */}
                <div style={{ padding: "30px 10px", marginBottom: "30px" }}>
                    <h2 style={{ fontSize: "22px", fontWeight: 800, marginBottom: "30px", color: "#fff", textAlign: "center" }}>Cara Bergabung</h2>
                    <div style={{ position: "relative" }}>
                        {/* Connecting Line */}
                        <div style={{ position: "absolute", left: "20px", top: "20px", bottom: "20px", width: "2px", background: "#4a3860" }}></div>
                        
                        {content.steps.map((step, idx) => (
                            <div key={idx} style={{ display: "flex", gap: "20px", marginBottom: "30px", position: "relative" }}>
                                <div style={{ width: "40px", height: "40px", borderRadius: "50%", background: "#ec4899", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold", flexShrink: 0, zIndex: 2, border: "4px solid #1e1b29" }}>{idx + 1}</div>
                                <div>
                                    <h3 style={{ color: "#f9a8d4", fontSize: "18px", fontWeight: "bold", marginBottom: "5px" }}>{step.title}</h3>
                                    <p style={{ color: "#cbd5e1", fontSize: "14px" }}>{step.desc}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* 12. PRICING & PAYMENT FORM */}
                <div style={{ background: "white", color: "#1e293b", padding: "40px 25px", borderRadius: "30px", marginBottom: "40px", boxShadow: "0 10px 40px rgba(0,0,0,0.1)", border: "1px solid #e2e8f0" }}>
                    <div style={{ textAlign: "center" }}>
                        <h2 style={{ marginTop: "20px", fontSize: "22px", fontWeight: 700, marginBottom: "20px" }}>Investasi untuk Kebahagiaan Cintamu</h2>
                        <p style={{ fontSize: "14px", color: "#64748b", marginBottom: "20px" }}>Biasanya, sesi private bersama saya dihargai:</p>
                        <div style={{ fontSize: "20px", textDecoration: "line-through", color: "#94a3b8", marginBottom: "5px" }}>{content.priceAnchor}</div>
                        <div style={{ fontSize: "42px", fontWeight: 900, color: "#ec4899", marginBottom: "10px" }}>{content.priceReal}</div>
                        <p style={{ fontSize: "13px", color: "#94a3b8", marginBottom: "30px" }}>(Hanya seharga sekali makan di mall untuk mengubah hidupmu)</p>
                    </div>

                    {/* FORM INPUTS */}
                    <div className="space-y-6 mt-8">
                        <div className="space-y-4">
                            <h3 className="font-bold text-lg flex items-center gap-2 text-pink-600">
                                <User className="w-5 h-5" /> Data Diri
                            </h3>
                            <div className="grid gap-4">
                                <div>
                                    <Label htmlFor="name" className="text-slate-700 font-semibold mb-1 block">Nama Lengkap</Label>
                                    <Input 
                                        id="name" 
                                        autoComplete="name"
                                        placeholder="Contoh: Siti Nurhaliza" 
                                        value={userName} 
                                        onChange={(e) => setUserName(e.target.value)} 
                                        className="bg-white text-slate-900 placeholder:text-slate-400 border-slate-300 focus:border-pink-500 h-12"
                                    />
                                </div>
                                <div className="grid md:grid-cols-2 gap-4">
                                    <div>
                                        <Label htmlFor="email" className="text-slate-700 font-semibold mb-1 block">Alamat Email (PENTING)</Label>
                                        <Input 
                                            id="email" 
                                            type="email" 
                                            autoComplete="email"
                                            placeholder="Untuk link webinar" 
                                            value={userEmail} 
                                            onChange={(e) => setUserEmail(e.target.value)} 
                                            className="bg-white text-slate-900 placeholder:text-slate-400 border-slate-300 focus:border-pink-500 h-12"
                                        />
                                    </div>
                                    <div>
                                        <Label htmlFor="phone" className="text-slate-700 font-semibold mb-1 block">Nomor WhatsApp</Label>
                                        <Input 
                                            id="phone" 
                                            type="tel" 
                                            autoComplete="tel"
                                            placeholder="0812xxxx" 
                                            value={phoneNumber} 
                                            onChange={(e) => setPhoneNumber(e.target.value)} 
                                            className="bg-white text-slate-900 placeholder:text-slate-400 border-slate-300 focus:border-pink-500 h-12"
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="space-y-4">
                            <h3 className="font-bold text-lg flex items-center gap-2 text-pink-600">
                                <CreditCard className="w-5 h-5" /> Metode Pembayaran
                            </h3>
                            <RadioGroup value={selectedPaymentMethod} onValueChange={setSelectedPaymentMethod} className="grid grid-cols-1 gap-4">
                                {paymentMethods.map((method) => (
                                    <Label key={method.code} className={`flex items-start p-4 border rounded-xl cursor-pointer transition-all ${selectedPaymentMethod === method.code ? 'border-pink-500 bg-pink-50 shadow-md ring-1 ring-pink-500' : 'border-slate-200 bg-white hover:border-slate-300'}`}>
                                        <RadioGroupItem value={method.code} id={method.code} className="mt-1 mr-4 border-slate-400 text-pink-600" />
                                        <div className="flex-1">
                                            <div className="font-bold text-slate-800 text-lg">{method.name}</div>
                                            <div className="text-sm text-slate-500">{method.description}</div>
                                        </div>
                                    </Label>
                                ))}
                            </RadioGroup>
                        </div>

                        <Button 
                            size="lg" 
                            className="w-full text-lg py-8 bg-gradient-to-r from-pink-600 to-purple-600 hover:from-pink-700 hover:to-purple-700 font-bold shadow-xl transition-all hover:scale-[1.01] active:scale-[0.99] text-white border-none mt-6"
                            onClick={handleCreatePayment}
                            disabled={loading}
                        >
                            {loading ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Memproses...</> : content.ctaButton}
                        </Button>
                        
                         <div className="flex items-center justify-center gap-4 text-xs text-slate-400 font-medium mt-4">
                            <div className="flex items-center gap-1">
                                <ShieldCheck className="w-3 h-3 text-green-600" /> Secure Payment
                            </div>
                            <div className="flex items-center gap-1">
                                <CheckCircle className="w-3 h-3 text-blue-600" /> Instant Access
                            </div>
                        </div>
                    </div>
                </div>

                {/* 13. FAQ SECTION */}
                <div style={{ marginBottom: "40px", padding: "0 10px" }}>
                    <h2 style={{ fontSize: "22px", fontWeight: 800, marginBottom: "25px", color: "#fff", textAlign: "center" }}>Pertanyaan Sering Diajukan</h2>
                    <div style={{ display: "flex", flexDirection: "column", gap: "15px" }}>
                        {content.faq.map((item, idx) => (
                            <div key={idx} style={{ background: "#1e1b29", padding: "20px", borderRadius: "15px", border: "1px solid #4a3860" }}>
                                <div style={{ color: "#f9a8d4", fontWeight: "bold", marginBottom: "10px", fontSize: "16px" }}>{item.q}</div>
                                <div style={{ color: "#cbd5e1", fontSize: "14px", lineHeight: 1.6 }}>{item.a}</div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* FOOTER */}
                <div style={{ textAlign: "center", paddingBottom: "30px", color: "#64748b", fontSize: "12px" }}>
                    <p style={{ marginBottom: "5px", fontWeight: "bold" }}>eL Vision Group</p>
                    <p>"Bahagia Adalah Koentji"</p>
                </div>
            </div>
        </div>
    );
};

export default WebinarIbu;